spring.application.name=GraosProsa
//->Continua-com-o-banco
//spring.jpa.hibernate.ddl-auto=update
//->Recria-o-banco
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
//spring.rabbitmq.host=rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

jwt.secret=${JWT_SECRET}
